[phases.setup]
aptPkgs = ["libsqlite3-0"]
nixPkgs = ["python3", "pip", "nodejs"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm install"
]

[start]
cmd = "python3 main_app.py"
