[build]
builder = "heroku/buildpacks:20"

[deploy]
startCommand = "python3 main_app.py"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"

[env]
# GitHub
REPO_GITHUB="Rabbit-Fur/System-by-FUR"
TOKEN_GITHUB="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" # 🔐 Setze diesen als Railway Secret
FUR_PAT="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"      # 🔐 Setze diesen als Railway Secret

# Discord
DISCORD_TOKEN="MTM2Mjg4ODY4ODk5MTczMTk2Mw.GLC4b-.6ccCTEKUvKKVoNFKwMBo3tFCWJNvR19OMfyvls"              # 🔐 Discord Bot Token → Railway Secret
DISCORD_CLIENT_ID="1362888688991731963"
DISCORD_CLIENT_SECRET="FqVmNprfXB_J15hBpgU-rXHGqBB9jvDB"      # 🔐 Client Secret → Secret
DISCORD_GUILD_ID="1344968805151019088"
DISCORD_CHANNEL_ID="1365580225945014385"
DISCORD_ADMIN_ROLE_ID="1345007778871115846"
ADMIN_ROLE_IDS="1345008298528604231"
R4_ROLE_IDS="1345008234527723520"
R3_ROLE_IDS="1345008403059179570"
DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/1363796827316420809/W7YjDFdVRcazdjranKBjHgQFY4KNTo578_wUhRCXZTk4leuMalPxnji33BzElz4eua-w"        # 🔐 Webhook → Secret
DISCORD_REDIRECT_URI="https://system-by-fur.up.railway.app/callback"

# Google
GOOGLE_CLIENT_ID="858610490497-6l1rp8bo51e7sd3pmklhpmbcrf9bfbft.apps.googleusercontent.com"
GOOGLE_PROJECT_ID="erudite-fusion-456918-h4"
GOOGLE_CLIENT_SECRET="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"       # 🔐 Google Secret
GOOGLE_AUTH_URI="https://accounts.google.com/o/oauth2/auth"
GOOGLE_TOKEN_URI="https://oauth2.googleapis.com/token"
GOOGLE_AUTH_PROVIDER_CERT_URL="https://www.googleapis.com/v1/certs"
GOOGLE_REDIRECT_URI="https://system-by-fur.up.railway.app/callback/google"

# Bot Settings
ENABLE_DISCORD_BOT="true"
OPENAI_API_KEY="proj_JZB3caGonxdtB4nflofV4dyC"             # 🔐 Dein OpenAI-API-Key → Secret

# Web
PORT="5000"
BASE_URL="https://system-by-fur.up.railway.app/"

# Sicherheit
SECRET_KEY="4fa028caf6d5c91645e37d8ce1400ec1451285bcceafaa3ccf273fcb3396f913"                 # 🔐 Setze als Railway Secret
FLASK_ENV="production"
SESSION_LIFETIME_MINUTES="60"
DATABASE_URL="sqlite:///fur.db"

# Logging
LOGTAIL_TOKEN="ZrWJhBk5J4XGZKXSCMgdM8Fb"              # 🔐 Logtail Token → Secret

# 🔒 KEINE DISCORD_TOKEN oder WEBHOOKS im Klartext!
