name: codex-ci
on:
  pull_request:
  push:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  codex:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Codex
        run: npm i -g @openai/codex

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps (best effort)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f package-lock.json ]; then npm ci || true; fi

      - name: Run Codex review (headless)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          codex exec --full-auto "Run lint fixes, add/update tests to reach 85% coverage, update CHANGELOG.md, and prepare a PR-ready summary."
