name: 🚀 Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: black . --check
      - run: isort . --check-only
      - run: flake8 .
      - run: pytest -v
      - name: Trigger Railway Deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          PROJECT_ID: ${{ secrets.RAILWAY_PROJECT }}
        run: |
          curl -X POST https://backboard.railway.app/project/${PROJECT_ID}/deploy \
            -H "Authorization: Bearer ${RAILWAY_TOKEN}" \
            -H "Content-Type: application/json"
